name: jenshel_app
description: "Una aplicación de tablero Kanban personal con diseño premium"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  glassmorphism_ui: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7


flutter:
  uses-material-design: true
